config/routes.rb
Akshi::Application.routes.draw do

  resources :sites

  resources :users do
    collection do
      get 'forgot_password'
      post 'send_reset'
    end
    member do
      get 'reset_password'
      put 'update_password'
      get 'courses'
    end

    resources :courses do
      member do
        post :enroll
        post :enroll_by_voucher
        get :pay_online
        get :payment_complete
        get :enter_voucher
        post :dropout
      end
    end
  end

  resources :packages do
    member do
      post :enroll
      post :dropout
      get :pay_online
      get :payment_complete
    end
  end

  resources :sessions

  resources :courses do
    member do
      get :users
      put :update_status
    end

    resources :lessons do
      collection do
        put :sort
      end

      member do
        delete :delete_attachment
        get :conversion_status
        get :preview
        get :download
      end
    end

    resources :topics

    resources :chats

    resource :live

    resources :schedules

    resources :vouchers do
      collection do
        post :generate
      end
    end

    resources :announcements

    resources :ratings

    resources :subjects do
      collection do
        put :sort
      end
    end

    resources :quizzes do
      member do
        post :complete
        get :results
      end
    end
  end

  resources :quizzes do
    resources :questions
    resources :responses
  end

  resources :questions do
    resources :answers
  end

  resources :services do
    collection do
      post :image_to_datauri
    end
  end

  resources :posts do
    resources :comments do
      put :update_status
    end
  end

  namespace :admin do
    resources :courses

    resources :comments

    resources :categories do
      collection do
        put :sort
      end
    end

    resources :collections do
      member do
        put :add_course
        put :remove_course
      end
    end

    resources :users do
      member do
        put :shadow
        get :courses
        post :courses
        put :enroll
      end
    end
  end

  match 'about' => 'pages#about'
  match 'terms_and_conditions' => 'pages#terms_and_conditions'
  match 'privacy_policy' => 'pages#privacy_policy'
  match 'register' => 'users#new'
  match 'login' => 'sessions#new'
  root :to => 'courses#index'

  # Protected downloads
  match '/lessons/uploads/:id/:file' => 'lessons#download'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  post_id    :integer
#  content    :text
#  email      :string(255)
#  status     :string(255)      default("review")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Comment < ActiveRecord::Base
  attr_accessible :content, :email, :post_id, :status, :user_id

  belongs_to :post
  belongs_to :user

  validates :email, :presence => true,
                    :format => {
                      :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
                    }, :allow_blank => true
  validates :content, :presence => true
  validates :post_id, :presence => true

  default_scope :order => 'comments.created_at DESC'

  scope :review, :conditions => {:status => 'review'}
  scope :approved, :conditions => {:status => 'approved'}

  self.per_page = 15

  def approved?
    self.status == 'approved'
  end

  def review?
    self.status == 'review'
  end

  def approve!
    self.update_attribute(:status, 'approved')
  end

  def reject!
    self.update_attribute(:status, 'rejected')
  end

  def review!
    self.update_attribute(:status, 'review')
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < AdminController

  def index
    @comments = Comment.review.paginate :page => params[:page],
                                       :per_page => params[:per_page]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :admin_authenticate, :only => [:update_status]
  before_filter :load_post

  def new
    @comment = @post.comments.new
  end

  def create
    attributes = params[:comment]
    if logged_in?
      attributes.merge!(:user_id => current_user.id, :email => current_user.email)
    end

    @comment = @post.comments.new(attributes)
    if @comment.save
      @success = true
      flash[:notice] = t('comments.under_review')
    else
      flash.now[:error] = t('comments.create_failed')
    end
  end

  def update_status
    @comment = Comment.find(params[:comment_id])
    case params[:status]
    when 'approve'
      @comment.approve!
      flash.now[:notice] =  t('comments.approved')
    when 'reject'
      @comment.reject!
      flash.now[:notice] =  t('comments.rejected')
    end
    @comments = Comment.review.paginate :page => params[:page],
                                        :per_page => params[:per_page]
  end

  private
  def load_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_index.html.erb
<%= render 'admin/nav' %>

<% if comments.present? %>
  <table class="table table-striped table-hover">
    <tbody>
      <% comments.each do |comment| %>
        <tr>
          <td class="user-icon">
              <% if comment.user.present? %>
                <%= image_tag comment.user.avatar(:icon), :class => 'thumbnail' %>
              <% else %>
                <%= image_tag 'users-placeholder-icon.png', :class => 'thumbnail' %>
              <% end %>
          </td>
          <td class="comment-details">
            <%= raw(comment.content) %>
            <br />
            <%= link_to comment.post.title, hash_path(post_path(comment.post)) %>
            <br />
            <div class="pull-left muted">
              <% if comment.user.present? %>
                <%= link_to comment.user.fullname, hash_path(user_path(comment.user,
                                                    :type => params[:type])) %>
              <% else %>
                <%= link_to comment.email, "mailto:#{comment.email}", :type => params[:type] %>
              <% end %>
              <%= t('topics.posted') %>
              <%= timeago comment.updated_at %>
            </div>
          </td>
          <td style="width: 150px; vertical-align: middle;">
            <%= link_to t('site.approve'),
                        post_comment_update_status_path(comment.post, comment,
                                                        :status => 'approve',
                                                        :type => 'admin',
                                                        :subtype => 'admin_comments'),
                        :method => :put, :remote => true, :confirm => t('site.confirm'),
                        :id => "approve_#{comment.id}", :class => 'btn btn-primary' %>
            <%= link_to t('site.reject'),
                        post_comment_update_status_path(comment.post, comment,
                                                        :status => 'reject',
                                                        :type => 'admin',
                                                        :subtype => 'admin_comments'),
                        :method => :put, :remote => true, :confirm => t('site.confirm'),
                        :id => "reject_#{comment.id}", :class => 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="pull-right">
    <%= page_navigation_links(comments) %>
  </div>
<% else %>
  <div class="alert">
    <%= t('comments.no_comments') %>
  </div>
<% end %>

app/views/admin/comments/index.js.erb
$('#content').html('<%= escape_javascript(render "admin/comments/index",
                                          :comments => @comments) %>');
$('#main-menu').html('<%= escape_javascript(render "layouts/main_menu") %>');
<%= render 'shared/page_flash' %>
window.initAjaxCSRF('<%= form_authenticity_token %>');