config/routes.rb
Akshi::Application.routes.draw do

  resources :sites

  resources :users do
    collection do
      get 'forgot_password'
      post 'send_reset'
    end
    member do
      get 'reset_password'
      put 'update_password'
      get 'courses'
    end

    resources :courses do
      member do
        post :enroll
        post :enroll_by_voucher
        get :pay_online
        get :payment_complete
        get :enter_voucher
        post :dropout
      end
    end
  end

  resources :packages do
    member do
      post :enroll
      post :dropout
      get :pay_online
      get :payment_complete
    end
  end

  resources :sessions

  resources :courses do
    member do
      get :users
      put :update_status
    end

    resources :lessons do
      collection do
        put :sort
      end

      member do
        delete :delete_attachment
        get :conversion_status
        get :preview
        get :download
      end
    end

    resources :topics

    resources :chats

    resource :live

    resources :schedules

    resources :vouchers do
      collection do
        post :generate
      end
    end

    resources :announcements

    resources :ratings

    resources :subjects do
      collection do
        put :sort
      end
    end

    resources :quizzes do
      member do
        post :complete
        get :results
      end
    end
  end

  resources :quizzes do
    resources :questions
    resources :responses
  end

  resources :questions do
    resources :answers
  end

  resources :services do
    collection do
      post :image_to_datauri
    end
  end

  resources :posts do
    resources :comments do
      put :update_status
    end
  end

  namespace :admin do
    resources :courses

    resources :comments

    resources :categories do
      collection do
        put :sort
      end
    end

    resources :collections do
      member do
        put :add_course
        put :remove_course
      end
    end

    resources :users do
      member do
        put :shadow
        get :courses
        post :courses
        put :enroll
      end
    end
  end

  match 'about' => 'pages#about'
  match 'terms_and_conditions' => 'pages#terms_and_conditions'
  match 'privacy_policy' => 'pages#privacy_policy'
  match 'register' => 'users#new'
  match 'login' => 'sessions#new'
  root :to => 'courses#index'

  # Protected downloads
  match '/lessons/uploads/:id/:file' => 'lessons#download'
end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id          :integer          not null, primary key
#  description :string(255)
#  start_time  :datetime
#  course_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  mode        :string(255)      default("LIVE")
#  lesson_id   :integer
#

class Schedule < ActiveRecord::Base
  attr_accessible :description, :start_time, :course_id, :mode, :lesson_id

  belongs_to :course
  belongs_to :lesson

  validates :description, :presence => true, :length => 4..80
  validates :start_time, :presence => true
  validates :course_id, :presence => true
  scope :active, where('courses.status = "published"').joins(:course)
  scope :upcoming, where('schedules.start_time > ?', 1.hour.ago)
  default_scope :order => 'schedules.start_time'
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_filter :authenticate
  before_filter :load_course
  before_filter :load_schedules
  before_filter :require_access
  before_filter :require_teacher, :only => [:create, :update, :destroy]

  def index
    @schedule = Schedule.new
  end

  def create
    start_time = params[:schedule][:start_time]
    parsed_start_time = parse_start_time(start_time)
    if parsed_start_time[:status] == 'failed'
      flash.now[:error] = parsed_start_time[:message]
    else
      @schedule = @course.schedules.new(params[:schedule]
                         .merge(:start_time => parsed_start_time[:message]))
      if @schedule.save
        @success = true
        flash.now[:notice] = t('schedules.scheduled')
      else
        flash.now[:error] = @schedule.errors.full_messages.first
      end
    end
  end

  def destroy
    @schedule = @course.schedules.find(params[:id])
    @schedule.delete
    flash.now[:notice] = t('schedules.deleted')
  end

  protected
  def load_course
    @course = Course.find(params[:course_id])
  end

  def parse_start_time(start_time)
    if start_time.blank?
      return {
        :status => 'failed',
        :message => 'Start time is required'
      }
    end
    parsed_time = Chronic.parse(start_time)
    if parsed_time.blank?
      return {
        :status => 'failed',
        :message => 'Start time is invalid'
      }
    end
    if parsed_time < Time.now
      return {
        :status => 'failed',
        :message => 'Start time should be in future'
      }
    end
    return {
      :status => 'success',
      :message => parsed_time
    }
  end

  def load_schedules
    @schedules = @course.schedules.upcoming
  end

  def require_access
    unless @course.users.include?(current_user)
      access_denied
    end
  end

  def require_teacher
    unless current_user.teacher?(@course.id)
      access_denied
    end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_index.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
  <h4><%= t('schedules.upcoming') %></h4>
</div>
<div class="modal-body scroll">
  <% if current_user.teacher?(course.id) %>
    <div class="well well-condensed">
      <%= form_for [course, schedule],
                   :html => {:class => 'form-inline', :remote => true} do |f| %>
        <%= f.text_field :description, :placeholder => t('schedules.placeholders.class_description'), :class => course.lessons.blank? ? 'schedule-description' : '' %>
        <%= f.text_field :start_time, :placeholder => t('schedules.placeholders.start_time'),
                         :class => course.lessons.blank? ? 'schedule-start' : '' %>
        <%= f.select :mode, options_for_select([ "LIVE", "RECORDED" ], "LIVE"), {},
                     {:class => course.lessons.blank? ? 'schedule-start' : ''} %>
        <% unless course.lessons.blank? %>
          <%= f.select :lesson_id, options_from_collection_for_select(course.lessons, 'id', 'name') %>
        <% end %>
        <%= f.submit 'Schedule', :class => 'btn btn-primary pull-right', :style=> course.lessons.blank? ? '' : "margin-right:60px" %>
      <% end %>
    </div>
  <% end %>

  <% if schedules.blank? %>
    <div class="alert">
      <%= t('schedules.no_classes') %>
    </div>
  <% else %>
    <table class="table table-striped table-hover">
      <tbody>
        <tr>
          <th>Description</th>
          <th>Start time</th>
          <% if current_user.teacher?(course.id) %>
            <th style="width: 50px; text-align: center;">Action</th>
          <% end %>
        </tr>
        <% schedules.each do |current_schedule| %>
          <% if current_schedule.persisted? %>
            <tr>
              <td><%= current_schedule.description %></td>
              <td><%= current_schedule.start_time.to_s :human %></td>
              <% if current_user.teacher?(course.id) %>
                <td>
                    <%= link_to 'Delete', course_schedule_path(course, current_schedule),
                                :class => 'btn btn-danger', :remote => true,
                                :method => :delete,
                                :confirm => t('site.confirm') %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal">
    <%= t('site.close') %>
  </button>
</div>

app/views/schedules/create.js.erb
$('#modal').html('<%= escape_javascript(render "schedules/index",
                                        :course => @course,
                                        :schedules => @schedules,
                                        :schedule => Schedule.new) %>');
<%= render 'shared/modal_flash' %>
$('.upcoming-count').text('<%= @course.schedules.upcoming.count %>');
window.initAjaxCSRF('<%= form_authenticity_token %>');

app/views/schedules/destroy.js.erb
$('#modal').html('<%= escape_javascript(render "schedules/index",
                                        :course => @course,
                                        :schedules => @schedules,
                                        :schedule => Schedule.new) %>');
<%= render 'shared/modal_flash' %>
$('.upcoming-count').text('<%= @course.schedules.upcoming.count %>');
window.initAjaxCSRF('<%= form_authenticity_token %>');

app/views/schedules/index.js.erb
$('#modal').html('<%= escape_javascript(render "schedules/index",
                                        :course => @course,
                                        :schedules => @schedules,
                                        :schedule => @schedule) %>');
$('#modal').modal();
<%= render 'shared/modal_flash' %>
window.initAjaxCSRF('<%= form_authenticity_token %>');